mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from mysite.views import hello, current_datetime, hours_ahead, \
                         current_datetime_template, more_current_datetime_template
from mysite.books.views import search
from mysite.contact.views import contact

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # mysite
    ('^hello/$', hello),
    ('^time/$', current_datetime),
    (r'^time/plus/(\d{1,2})/$', hours_ahead),
    ('^template_time/$', current_datetime_template),
    ('^more_time/$', more_current_datetime_template),

    # books
    (r'^search/$', search),

    # contact
    (r'^contact/$', contact),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/mysite/books/models.py
from django.db import models

class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()

	def __unicode__(self):
		return self.name


	class Meta:
		ordering = ['name']


class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField('e-mail', blank=True)

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField(blank=True, null=True)

	def __unicode__(self):
		return self.title

mysite/mysite/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())

        if num_words < 4:
            raise forms.ValidationError("Not enough words!")

        return message

mysite/mysite/books/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from mysite.books.models import Book


def search_form(request):
    return render_to_response('books/search_form.html')

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('books/search_results.html',
                                     {'books': books, 'query': q})

    return render_to_response('books/search_form.html', {'errors': errors})

mysite/mysite/contact/views.py
from django.shortcuts import render_to_response
from mysite.contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                      ['siteowner@example.com'])
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render_to_response('contact/contact_form.html', {'form': form})

mysite/mysite/views.py
from django.template.loader import get_template
from django.template import Context
from django.http import Http404, HttpResponse
from django.shortcuts import render_to_response
import datetime



def hello(request):
    # say hello
    return HttpResponse("Hello, welcome to my %s page" % request.path)

# current_datetime w/o template
def current_datetime(request):
    # get the current time
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    
    return HttpResponse(html)

# current_datetime w/ template
def current_datetime_template(request):
    now = datetime.datetime.now()
    t = get_template('current_datetime.html')
    html = t.render(Context({'current_date': now}))
    return HttpResponse(html)

def more_current_datetime_template(request):
    now = datetime.datetime.now()
    return render_to_response('more_current_datetime.html', {'current_date': now})

def hours_ahead(request, hours):
    # time ahead by said hours
    try:
        hours = int(hours)
    except ValueError:
        raise Http404()

    dt = datetime.datetime.now() + datetime.timedelta(hours=hours)
    return render_to_response('hours_ahead.html', {'hours_offset': hours, 'next_time': dt})

mysite/mysite/templates/base.html
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
        <style type="text/css">
            ul.errorlist {margin: 0; padding: 0;}
            .errorlist li {background-color: red; color: white; display: block; font-size: 10px; margin: 0 0 3px; padding: 4px 5px;}
        </style>
	</head>
	<body>
		<h1>My helpful timestamp site</h1>

		{% include "nav.html" %}
		
		{% block content %}{% endblock %}

		{% block footer %}
		<p>Thanks for visiting.</p>
		{% endblock %}		

	</body>
</html>

mysite/mysite/templates/books/search_form.html
{% extends "base.html" %}

{% block title %}Book Search{% endblock %}

{% block content %}
    <h4>Search</h4>

    {% if errors %}
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="" method="get">
        <input type="text" name="book">
        <input type="submit" value="Search">
    </form>

{% endblock %}

mysite/mysite/templates/books/search_results.html
{% extends "base.html" %}

{% block title %}Book Search Results{% endblock %}

{% block content %}
    <h4>Search Results</h4>
    <p>You searched for: <strong>{{ query }}</strong></p>
    
    {% if books %}
        <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
        <ul>
            {% for book in books %}
            <li>{{ book.title }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books matched your search criteria.</p>
    {% endif %}

{% endblock %}

mysite/mysite/templates/contact/contact_form.html
{% extends "base.html" %}

{% block title %}Contact Form{% endblock %}

{% block content %}
<h1>Contact us</h1>
{% if form.errors %}<p style="color: red;">Please correct the error{{ form.errors|pluralize }} below.</p>{% endif %}

<form action="" method="post">
    <div class="field">
        {{ form.subject.errors }}
        <label for="id_subject">Subject:</label>
        {{ form.subject }}
    </div>
    <div class="field">
        {{ form.email.errors }}
        <label for="id_e-mail">Your email address:</label>
        {{ form.email }}
    </div>
    <div class="field">
        {{ form.message.errors }}
        <label for="id_message">Message:</label>
        {{ form.message }}
    </div>
    <input type="submit" value="Submit">
</form>
{% endblock %}

mysite/mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}Current Date &amp; Time{% endblock %}

{% block content %}
	<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/mysite/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future Time{% endblock %}

{% block content %}
	<p>In {{ hours_offset }} hour(s), it will be {{ next_time }} CST.</p>
{% endblock %}

mysite/mysite/templates/more_current_datetime.html
{% extends "base.html" %}

{% block title %}Current Date &amp; Time{% endblock %}

{% block content %}
	<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/mysite/templates/nav.html
<a href="/template_time">Time</a>,&nbsp;&nbsp;
<a href="/more_time">More Time</a>,&nbsp;&nbsp;
<a href="/time/plus/2">Future Time</a>,&nbsp;&nbsp;
<a href="/search">Book Search</a>,&nbsp;&nbsp;
<a href="/contact">Contact</a>